<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <VersionPrefix>0.2.6</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == ''">pre</VersionSuffix>
  </PropertyGroup>
</Project>
